"""
Repository Ports

Architectural Intent:
- Port interfaces for data persistence (Hexagonal Architecture)
- Defined in domain layer, implemented in infrastructure layer
- Protocol-based for dependency inversion

Key Design Decisions:
1. Each aggregate has its own repository port
2. Methods return domain entities or lists of entities
3. No framework-specific types in domain layer
"""

from typing import Protocol, Optional, List
from uuid import UUID

from domain.entities import Account, Contact, Opportunity, Lead, Case


class AccountRepositoryPort(Protocol):
    async def save(self, account: Account) -> Account: ...

    async def get_by_id(self, account_id: UUID) -> Optional[Account]: ...

    async def get_by_name(self, name: str) -> Optional[Account]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> List[Account]: ...

    async def get_by_owner(self, owner_id: UUID) -> List[Account]: ...

    async def get_by_industry(self, industry: str) -> List[Account]: ...

    async def delete(self, account_id: UUID) -> None: ...


class ContactRepositoryPort(Protocol):
    async def save(self, contact: Contact) -> Contact: ...

    async def get_by_id(self, contact_id: UUID) -> Optional[Contact]: ...

    async def get_by_email(self, email: str) -> Optional[Contact]: ...

    async def get_by_account(self, account_id: UUID) -> List[Contact]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> List[Contact]: ...

    async def get_by_owner(self, owner_id: UUID) -> List[Contact]: ...

    async def delete(self, contact_id: UUID) -> None: ...


class OpportunityRepositoryPort(Protocol):
    async def save(self, opportunity: Opportunity) -> Opportunity: ...

    async def get_by_id(self, opportunity_id: UUID) -> Optional[Opportunity]: ...

    async def get_by_account(self, account_id: UUID) -> List[Opportunity]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> List[Opportunity]: ...

    async def get_by_owner(self, owner_id: UUID) -> List[Opportunity]: ...

    async def get_by_stage(self, stage: str) -> List[Opportunity]: ...

    async def get_open_opportunities(self) -> List[Opportunity]: ...

    async def get_by_close_date_range(
        self, start_date: datetime, end_date: datetime
    ) -> List[Opportunity]: ...

    async def delete(self, opportunity_id: UUID) -> None: ...


class LeadRepositoryPort(Protocol):
    async def save(self, lead: Lead) -> Lead: ...

    async def get_by_id(self, lead_id: UUID) -> Optional[Lead]: ...

    async def get_by_email(self, email: str) -> Optional[Lead]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> List[Lead]: ...

    async def get_by_status(self, status: str) -> List[Lead]: ...

    async def get_by_owner(self, owner_id: UUID) -> List[Lead]: ...

    async def get_unqualified_leads(self) -> List[Lead]: ...

    async def delete(self, lead_id: UUID) -> None: ...


class CaseRepositoryPort(Protocol):
    async def save(self, case: Case) -> Case: ...

    async def get_by_id(self, case_id: UUID) -> Optional[Case]: ...

    async def get_by_case_number(self, case_number: str) -> Optional[Case]: ...

    async def get_by_account(self, account_id: UUID) -> List[Case]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> List[Case]: ...

    async def get_by_status(self, status: str) -> List[Case]: ...

    async def get_by_owner(self, owner_id: UUID) -> List[Case]: ...

    async def get_open_cases(self) -> List[Case]: ...

    async def delete(self, case_id: UUID) -> None: ...


from datetime import datetime
